### ISSUE TITLE
Some tests in BioPerl master branch fail

### ISSUE THREAD

**Issue by hlapp** [bioperl/bioperl-docker#7]
Currently there are multiple test failures on the bioperl/bioperl-live@master branch, including the following:
* bioperl/bioperl-live#292
* bioperl/bioperl-live#293
* ~~bioperl/bioperl-live#295~~
* ~~bioperl/bioperl-live#296~~

Right now we therefore install without running the tests so we have a new bioperl/bioperl:latest container off of master since the migration to Dist::Zilla. However, as these get fixed, need to turn on running the tests again.

**Comment by carandraug** [comment]
The two remaining failing tests are for two modules that have now been moved out of the BioPerl distribution. The failing tests remain, only somewhere else.

On issue #5 you mentioned it would make more sense to have the docker include all the bioperl distributions, which I guess would include those two, so I'm not sure if you want to close the issue just yet.
